#!/bin/bash
swarm -f orf1ab_codon_mapping.swarm -g 100.0 --time=0-04:00:00 --partition norm --module singularity --logdir swarm_output #  quick # norm
swarm -f s_codon_mapping.swarm -g 100.0 --time=0-04:00:00 --partition norm --module singularity --logdir swarm_output #  quick # norm
swarm -f orf3a_codon_mapping.swarm -g 100.0 --time=0-04:00:00 --partition norm --module singularity --logdir swarm_output #  quick # norm
swarm -f orf7a_codon_mapping.swarm -g 100.0 --time=0-04:00:00 --partition norm --module singularity --logdir swarm_output #  quick # norm
swarm -f orf7b_codon_mapping.swarm -g 100.0 --time=0-04:00:00 --partition norm --module singularity --logdir swarm_output #  quick # norm
swarm -f n_codon_mapping.swarm -g 100.0 --time=0-04:00:00 --partition norm --module singularity --logdir swarm_output #  quick # norm

